"""updated zone_type column

Revision ID: 05038af6d2dd
Revises: 5656af14cda4
Create Date: 2025-07-20 04:12:57.614541
гостович
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05038af6d2dd"
down_revision: Union[str, Sequence[str], None] = "5656af14cda4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

triptypes_enum = sa.Enum("YELLOW", "GREEN", name="triptypes")


def upgrade() -> None:
    """Upgrade schema."""
    triptypes_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "file_metadata", sa.Column("trip_type", triptypes_enum, nullable=True)
    )
    op.drop_column("file_metadata", "zone_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_metadata",
        sa.Column("zone_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("file_metadata", "trip_type")
    # ### end Alembic commands ###
