"""first revision

Revision ID: 1524fac8a368
Revises:
Create Date: 2025-07-10 03:34:34.461910

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1524fac8a368"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_metadata",
        sa.Column("file_metadata_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_type", sa.Enum("CSV", "PARQUET", name="allowedextensions"), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("storage_path_processed", sa.String(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "PROCESSING", "PROCESSED", "FAILED", name="filestatus"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("file_metadata_id"),
    )
    op.create_index(op.f("ix_file_metadata_file_name"), "file_metadata", ["file_name"], unique=False)
    op.create_index(op.f("ix_file_metadata_file_type"), "file_metadata", ["file_type"], unique=False)
    op.create_index(op.f("ix_file_metadata_status"), "file_metadata", ["status"], unique=False)
    op.create_index(op.f("ix_file_metadata_storage_path"), "file_metadata", ["storage_path"], unique=False)
    op.create_index(op.f("ix_file_metadata_storage_path_processed"), "file_metadata", ["storage_path_processed"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_metadata_storage_path_processed"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_storage_path"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_status"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_file_type"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_file_name"), table_name="file_metadata")
    op.drop_table("file_metadata")
    # ### end Alembic commands ###
