"""new columns for file_metadata

Revision ID: 5656af14cda4
Revises: 1524fac8a368
Create Date: 2025-07-20 04:03:00.643171

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5656af14cda4"
down_revision: Union[str, Sequence[str], None] = "1524fac8a368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_metadata", sa.Column("zone_type", sa.String(), nullable=True))
    op.add_column("file_metadata", sa.Column("year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_metadata", "year")
    op.drop_column("file_metadata", "zone_type")
    # ### end Alembic commands ###
